// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yllqbvettufqjdtvlefq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsbHFidmV0dHVmcWpkdHZsZWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODA1NjMsImV4cCI6MjA2NDg1NjU2M30.iOtd9LqZpCY814nYajzG76jLO63sABWRoRXghNaYSAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);